# Generated by Django 6.0 on 2025-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('order_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('is_promo', models.BooleanField(default=False)),
                ('refund_flag', models.BooleanField(default=False)),
                ('device', models.CharField(blank=True, default='', max_length=64)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='UserClusterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=64)),
                ('cluster_id', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order_count', models.PositiveIntegerField()),
                ('avg_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refund_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_order_time', models.DateTimeField()),
                ('top_category', models.CharField(blank=True, default='', max_length=128)),
                ('top_channel', models.CharField(blank=True, default='', max_length=64)),
                ('top_device', models.CharField(blank=True, default='', max_length=64)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cluster_id', '-total_amount'],
                'indexes': [models.Index(fields=['cluster_id'], name='segmentatio_cluster_9c54a0_idx'), models.Index(fields=['run_at'], name='segmentatio_run_at_de365e_idx')],
            },
        ),
    ]
